### PR TITLE
#37637480 setup and integrate create-react-app templates and environment

### PR DESCRIPTION
**Pull request by torsami77**
## Description
setup and integrate create-react-app templates and environment

## How Has This Been Tested?
- In your terminal, run git clone https://github.com/BuildForSDG/team-010-frontend.git
- Run cd team-010-frontend
- Run git fetch origin gh-pages
- Run git checkout origin/gh-pages
- Run npm install
- Run npm run test to run sample test
- Run npm start to run react environment

## Checklist:
- setup react environment
- avails react-component template
- implements test with jest
- creates test directories
- configures eslint and prettierrc definitions 
- establishes gh-pages as test deploy environment

### CODE REVIEW

**Review by RuthChisom — DISMISSED** [review]
Approve

**Review by Biosmatrix — APPROVED** [review]
Looking good, approve

**Comment by nues1979** [comment]
Great  Approve

**Comment by nues1979** [comment]
great

**Review by nues1759 — APPROVED** [review]
great

**Review by sundaynwoye — APPROVED** [review]

**Comment by sundaynwoye** [comment]
Great

**Review by sundaynwoye — APPROVED** [review]

**Comment by sundaynwoye** [comment]
Good work

**Review by RuthChisom — APPROVED** [review]
Approve.

**Pull request merged**
