### PR TITLE
hot-fix

### LINKED ISSUE #3: [CHORE] Project Scaffolding
## Title: Project Scaffolding for ReactJS
- setup and integrate create-react-app templates

- setup react environment

- Setup EsLint and prettierrc definitions including necessary dependencies

- Setup testing with Jest

- Setup Heroku deployment

### PR DESCRIPTION
**Pull request by torsami77**
## Description
Quick fix to delete app.js.

### CODE REVIEW

**Review by orimdominic — DISMISSED** [review]

**Review by orimdominic — DISMISSED** [review]

**Review by orimdominic — COMMENTED** [review]
I pulled this to my local.
I can find neither  `App.js` nor `app.js` under `src` under the PR branch

I think this is what you should do

1. Make a copy of the contents of the desired file (file to be retained) somewhere else
2. Delete both files `App.js` and `app.js`
3. Make a commit
4. Create the desired file again with its contents in its former directory, the way it was previously
5. Make a commit
6. Push and make a PR

**Comment by torsami77** [comment]
@sudo-kaizen https://github.com/BuildForSDG/team-010-frontend/tree/hot-fix/src please could you confirm that you can see the appropriate files on the remote version? I think you should clone the repo afresh

**Comment by orimdominic** [comment]
> @sudo-kaizen https://github.com/BuildForSDG/team-010-frontend/tree/hot-fix/src please could you confirm that you can see the appropriate files on the remote version? I think you should clone the repo afresh

missingfiles
Please find attached a screenshot of the `ls src/` command for the PR commit. I cant find both `App.js` and `app.js`

**Comment by torsami77** [comment]
@sudo-kaizen , could you check now, I have followed procedure

**Review by orimdominic — COMMENTED** [review]
@torsami77 correct, but there is no `App.js` in the `src` folder. There's no `App.js` in the [hot-fix remote PR branch](https://github.com/BuildForSDG/team-010-frontend/tree/hot-fix/src) too

**Comment by sudo-kaizen** [comment]
The latest commit works on my local

**Review by orimdominic — APPROVED** [review]
[This commit](https://github.com/BuildForSDG/team-010-frontend/pull/7/commits/aa6380baa71ee47833e9b9a8aeada023baa6cf48) works on my local

**Review by Biosmatrix — APPROVED** [review]

**Review by RuthChisom — APPROVED** [review]
Please proceed

**Pull request merged**
