### PR TITLE
Auth page

### PR DESCRIPTION
**Pull request by RuthChisom**
## Description
Login Authentication
Fixes #(Authentication)

Dependencies
npm install --save styled-components

## How Has This Been Tested?
npm install
npm start

## Checklist:

- [x ] My code follows the style guidelines of this project
- [ x ] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] I have added necessary inline code documentation
- [ ] I have added tests that prove my fix is effective and that this feature works
- [ x ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by sudo-kaizen** [comment]
I cannot run the app. I get this error:
`Cannot find file: 'App.js' does not match the corresponding name on disk: '.\src\app.js'.
`
I think you should merge/sync your code with the correction on the `hot-fix` branch

**Review by orimdominic — CHANGES_REQUESTED** [review]
I cannot run the app on my local. After executing
```bash
git fetch upstream
git checkout upstream/auth-page -f
```
I get this error:
`Cannot find file: 'App.js' does not match the corresponding name on disk: '.\src\app.js'.`

This problem cannot be solved by merely changing the `app.js` to `App.js`
I think you should merge/sync your code with the correction on the hot-fix branch

How to achieve this:

1. Make sure you are on your local branch `auth-page`
2. Execute `git fetch upstream` to pull the latest changes from the `upstream/develop` branch to your local
3. Merge `upstream/develop` to your local `auth-page` branch by executing `git merge upstream/develop` while still on your local `auth-page` branch
4. Fix conflicts if there are any
5. Check your code to make sure it still works as required/requested. Make changes and commit if required
6. Push the `auth-page` branch to your remote repo and make a PR

**Comment by RuthChisom** [comment]
What you have here is app.js not App.js
Please check that you have pulled the latest changes.

**Comment by orimdominic** [comment]
> What you have here is app.js not App.js
> Please check that you have pulled the latest changes.

I have pulled the latest. There was an error with the names `App.js` and `app.js` ([see here](https://github.com/BuildForSDG/team-010-frontend/pull/7)) and it was fixed and merged to branch `develop`. `app.js` was changed to `App.js` and that's the latest.

@torsami77 could you check this out please?

**Comment by RuthChisom** [comment]
@sudo-kaizen Sorry, pls try to pull again. I just pushed some changes

**Comment by orimdominic** [comment]
@RuthChisom Apologies as I should have shown you how to make the necessary changes. As you can see, even Travis is rejecting the PR

I have reviewed your latest changes and I am still getting the error. I have updated my request for changes ([see here](https://github.com/BuildForSDG/team-010-frontend/pull/8#pullrequestreview-413085071)) to include steps on how you can resolve this issue.

Please follow the steps and mention me if you have any issues.

**Review by orimdominic — APPROVED** [review]

**Review by nues1759 — APPROVED** [review]
ok

**Comment by WillDera** [comment]
Ok

**Review by WillDera — APPROVED** [review]
ok

**Review by WillDera — APPROVED** [review]
ok

**Review by WillDera — APPROVED** [review]
Ok

**Review by WillDera — APPROVED** [review]
Ok

**Review by WillDera — APPROVED** [review]
Ok

**Pull request merged**
