### PR TITLE
setup frontend ci-cd pipelines

### PR DESCRIPTION
**Pull request by torsami77**
#### What does this PR do?
- modifies webpack output
- configures build process for deployment on heroku
- configures containerized test on TravisCI
- Configures Test Coverage on coveralls.io

#### How should this be manually tested?
- Check heroku frontend staging - https://staged-team-010-frontend.herokuapp.com/
- check travisCI build - https://travis-ci.com/github/BuildForSDG/team-010-frontend/builds/166576292
- check coveralls coverage - https://coveralls.io/builds/30840562

#### Any background context you want to provide?
- Please take note that all test env variable would henceforth be added on .travis.yml file
- please Ignore the currently unkown badges on the branch, the badges can only reflect the develop branch which would begin after merge

#### Questions:

### CODE REVIEW

**Review by RuthChisom — DISMISSED** [review]

**Review by orimdominic — DISMISSED** [review]
I have 
- checked heroku frontend staging - https://staged-team-010-frontend.herokuapp.com/ and it is okay
- checked travisCI build - https://travis-ci.com/github/BuildForSDG/team-010-frontend/builds/166576292 and it passes
- checked coveralls coverage - https://coveralls.io/builds/30840562 and it passes too

**Review by RuthChisom — DISMISSED** [review]
Approve!!

**Review by Biosmatrix — CHANGES_REQUESTED** [review]
@torsami77 great job, however there are few things i want you to fix
1. Fix the linting errors
2. Move the @testing-library and coveralls packages to devDependencies
3. remove the node-sass package as the project is using the styled-components package

**Review by Biosmatrix — DISMISSED** [review]

**Review by Biosmatrix — APPROVED** [review]
Approved

**Review by RuthChisom — APPROVED** [review]
Approve

**Review by WillDera — APPROVED** [review]
Ok

**Pull request merged**
