### PR TITLE
#4 Build homepage for app

### LINKED ISSUE #4: [FEATURE] Homepage
**Story Title**: A registered/unregistered user should be able to land on a homepage

 **As a** registered/unregistered user ,
**I want** to be able to land on a well-designed homepage ,
**So that** I would be able to access the web app and its functions

**Acceptance Criteria**
```
Scenario: 
GIVEN a registered/unregistered user
WHEN a registered/unregistered user lands on the homepage
THEN the registered/unregistered user should have an access to all the information on the web page
```

**Dev Notes:**
The registered/unregistered user should be able to land easily on the homepage.

**Design Notes:**
A very detailed and attractive UI with a good UX.

### PR DESCRIPTION
**Pull request by orimdominic**
## Description
 A registered/unregistered user should be able to land on a homepage

## New dependencies
- `materialize-css`

This PR fixes #4

## Screenshots 

homepage-responsive

#### How should this be manually tested?
- Get this branch to local with `git fetch upstream`
- Run `git checkout upstream/homepage-responsive` on your terminal
- Install dependencies `npm install`
- Run the app `npm start`

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added necessary inline code documentation
- [x] New and existing unit tests pass locally with my changes

## Extra notes
- We'll need to discuss the exact text and links to add to the page on slack or any other workgroup channel

### CODE REVIEW

**Review by RuthChisom — DISMISSED** [review]
Approve!

**Review by nues1759 — DISMISSED** [review]
looking Good

**Review by nues1759 — APPROVED** [review]
looking good 
 but i believe the page should have more items for sale

**Comment by orimdominic** [comment]
> looking good
> but i believe the page should have more items for sale

It is not the landing page. It is the home page.
A modification may be to add a link to the markets page
What do you think?

**Pull request closed without merging**
