### PR TITLE
Landingpage

### PR DESCRIPTION
**Pull request by nues1759**
## Description
Please include a summary of the change and relevant motivation and context. 
List any dependencies that are required for this change.

All pull requests should be related to open issues. Indicate the issue(s) bellow and remove this line:
Fixes #(issue number 1) #(issue number 2 if applicable)

## How Has This Been Tested?
Please describe in detail how you tested your changes.
Include details of your testing environment, and the tests you ran to see how your change affects other areas of the code etc.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added necessary inline code documentation
- [ ] I have added tests that prove my fix is effective and that this feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by orimdominic** [comment]
I thought @sudo-kaizen was the one who was assigned this feature

**Comment by nues1759** [comment]
> I thought @sudo-kaizen was the one who was assigned this feature


Ruth Chisom <notifications@github.com> | Ruth Chisom <notifications@github.com> | May 11, 2020, 10:09 AM (3 days ago) |   |  
-- | -- | -- | -- | --
Ruth Chisom <notifications@github.com>
to BuildForSDG/team-010-frontend, me, Assign | to BuildForSDG/team-010-frontend, me, Assign
to BuildForSDG/team-010-frontend, me, Assign

but it can be deleted if the need arise .

**Comment by orimdominic** [comment]
Alright. I'll review it still

**Comment by RuthChisom** [comment]
@neus mistakenly pushed his market page work into your branch. Please still review

**Review by orimdominic — CHANGES_REQUESTED** [review]
There was an bug caused by the naming of the `App.js` file which prevented the app from building and gave the error
```
Failed to compile
./src/index.js
Cannot find file: 'app.js' does not match the corresponding name on disk: '.\src\App.js'.
```
After pulling your branch to my local, I got the error. This is because there are two files `App.js` and `app.js` and Windows-based computers cannot distinguish between the two. [See here](https://github.com/BuildForSDG/team-010-frontend/pull/7) for more information and that it was also resolved.

To fix:
1. Make sure you are on your local branch `homepage`
2. Execute `git fetch upstream` to pull the latest changes from the `upstream/develop` branch to your local
3. Merge `upstream/develop` to your local `homepage` branch by executing `git merge upstream/develop` while still on your local `develop` branch
4. Fix conflicts if there are any
5. Check your code to make sure it still works as required/requested. Make changes and commit if required
6. Push the `homepage` branch to your remote repo and make a PR

**Comment by orimdominic** [comment]
I also suggest that you should rename your branch to avoid conflicts

**Comment by RuthChisom** [comment]
@sudo-kaizen why do you suggest a rename? Do we have another branch with same name?
I've resolved all conflicts though.

**Review by RuthChisom — DISMISSED** [review]
Approve!!

**Review by orimdominic — DISMISSED** [review]

**Pull request closed without merging**
